GeneralOption:
  # 频道选项
  ChannelOption:
    # 默认频道
    DefaultChannel: "全体"
    Channels:
      - "全体"
      - "城镇"
  PlayerChatFormat: "&f[&6%channel%&f][&6%town_name%&f]%player_name%: %message%"

# 物品星级
WeaponLevelOption:
  # 表达式
  Pattern: '星级: (\d+)阶(\d+)星'
  # 升级描述
  UpgradeLore: '&f > 星级: &e$1阶$2星'